### ISSUE TITLE
Shell not looking like yours, I am not sure what I am doing wrong.

### ISSUE THREAD

**Issue by christianpeirson** [Jac-Zac/paleofetch-mac-prettier#2]
![Screenshot 2023-02-03 at 19 49 08](https://user-images.githubusercontent.com/112232564/216736245-aeff6203-308f-4903-b31f-ea4fef03db15.JPG)

I installed the program, I have Nerd Fonts installed and active in Iterm2.

What else do I have to do to get my shell looking like yours?

Do you use other scripts and programs to make your iterm2 look that way in your screenshot?

**Comment by Jac-Zac** [comment]
I'm not really sure on how to help could you also try to install my same font and see if that helps ? With: ```brew font-inconsolata-lgc-nerd-font``` and than use that. Also keep in mind that this is just a fork of the [original project](https://gitlab.com/DesantBucie/paleofetch-mac) so I haven't even looked at the entire code. also I'm on m1 and I haven't test it on intel, when I have access to an intel mac I'll try to fix it if that is the problem

**Comment by Jac-Zac** [comment]
I have made some new changes you could try to install the new version, remember that for the first time you run it it might look strange because it has to create the new cache

**Comment by jonstump** [comment]
This happens to me as well, but it only happens when it first runs and needs to cache. After it has cached it runs as "expected" I say "expected" because I have a different issue with a rogue 0 showing up. Little confused as to where the config file installs on mac to check if it's something there.

I use iterm2 and a nerd font, so I'm unsure as to why I'm seeing this as well. I can also confirm once cached it stops being an issue with subsequent runs (because well cached). I attached a screenshot running it resetting the cache and then again showing how it looks correct with the cache.

![CleanShot 2023-02-04 at 10 06 50@2x](https://user-images.githubusercontent.com/59323850/216782781-171da182-da25-407a-b34b-dbf7db0eba17.png)

**Comment by Jac-Zac** [comment]
Where is the problem with the 0 ? You I don't really know how I should fix the problem related to the cache since this is not even my original project but just a fork.

**Comment by jonstump** [comment]
I'm not sure. I've investigated it a little bit, but all I've been able to find from the install is the cache file itself, which didn't help me, and swapping to your font in iterm2 still shows the zero on my end.

I just happened to notice the open issue when I came here from reddit and wanted to add what I was seeing as I figured it might be helpful to yourself and @Graveside2022 regarding the wonkiness of what they were seeing. 

I know for some, like myself, I don't see this as a huge deal, looks weird when you wipe the cache, but then it runs fine. I only mentioned the zero because I suddenly noticed it when I was dropping in my screenshot 😅

**Comment by Jac-Zac** [comment]
Oky have you tried to git pull to the latest version because perhaps I made a typo and added a zero where it shouldn't have been. But since I don't see it know maybe it was in a previous version. If it still shows up after you: ```git pull && make install``` I'm not really sure how to help. And about the chache I'm not really sure on how to solve it maybe when I'll have more time I'll try to fix it

**Comment by jonstump** [comment]
I just did a `git pull && make install` and I'm not seeing any changes in behavior.

**Comment by Jac-Zac** [comment]
Oky I really don't know how to fix that 0 if anyone else gets it let me know. I'm not really sure on how to replicate it on my mac

**Comment by DesantBucie** [comment]
I think I can tell you what's wrong.

The printing is done in main. Your added functions instead of returning string via pointer to the main, they print stuff. This is why when the cache file is created the problem no longer exists, although i don't know how it reads the stuff from printfs, and saves it to cache file.

Small changes needed. The only problem i'm having is with the lower bar. You shouldn't have to compansate for the width of the logo. The empty line at the bottom of the logo has to be deleted, or program thinks it still has logo to print and prints empty line. Also you have to change logo_linelenght variable to 40, so, because you added spaces to the logo.

Result(i haven't installed fonts): 
![image](https://user-images.githubusercontent.com/46130107/226145061-c30d0abb-89f1-4056-9349-e767ff0b8e9b.png)

I've made pull request: https://github.com/Jac-Zac/paleofetch-mac-prettier/pull/3

**Comment by DesantBucie** [comment]
https://github.com/Jac-Zac/paleofetch-mac-prettier/pull/3

**Comment by Jac-Zac** [comment]
Oky I'm actually not really to invested in the project since I have a lot of things to do and I mainly did it because I wanted a faster neofetch : - ) , so I didn't really look too much into the code and just adapted it so that it worked for me. But thanks a lot
